name: Deploy Java App to AWS EC2 and run Docker container
on:
  push:
    branches:
      - develop
jobs:
  Build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
   # - name: Install Java
    #  uses: actions/setup-java@v3
     # with:
    #    java-version: '11'
    #    distribution: 'temurin'
    #    cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests
   
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
     
    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        tags: fambudget/fambudget_back:latest
# tags: fambudget/fambudget_back:${{github.run_number}}
      
  Deploy:
    needs: Build
    runs-on: ubuntu-22.04
  
    steps:
      - uses: actions/checkout@v3
      - name: Deploy in EC2
        env:
            DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USER }}
            DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            PRIVATE_KEY: ${{ secrets.SSH_AWS_FAMBUDGET  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.USER_NAME  }}

        run: |
           echo "$PRIVATE_KEY" > fambudget.pem && chmod 600 fambudget.pem
           ssh -o StrictHostKeyChecking=no -i fambudget.pem ${USER_NAME}@${HOSTNAME}    ' 
             docker login --username=${DOCKER_HUB_USERNAME} --password=${DOCKER_HUB_PASSWORD}
             sudo docker run -d --name 'fambudget_back' -p 8080:8080 -p 25:25 fambudget/fambudget_back:latest          
            '       

# sudo docker run -d --name 'fambudget_back' -p 8080:8080 fambudget/fambudget_back:${{github.run_number}}

